### ISSUE TITLE
listGEOData -startdate Flag: Unable to Reach Rewind Point

### ISSUE THREAD

**Issue by xubrianna** [PavlidisLab/Gemma#1300] opened 2024-12-03 17:52 UTC
`listGEOData -startdate` unable to locate the `-startdate` of GEO record search. Seems to function fine for more recent start dates, but starts to break with older start dates.

`2024-11-29 15:23:05,708 INFO 2972202 [main] u.g.c.a.GeoGrabberCli.seekRewindPoint(393) | Seeking rewind point from Fri May 14 00:00:00 PDT 2021                                          
2024-11-29 15:23:10,036 INFO 2972202 [main] u.g.c.a.GeoGrabberCli.seekRewindPoint(404) | Currently at GSE283021 released on Thu Nov 28 00:00:00 PST 2024                                 
2024-11-29 15:23:12,907 INFO 2972202 [main] u.g.c.a.GeoGrabberCli.seekRewindPoint(404) | Currently at GSE247076 released on Fri Nov 01 00:00:00 PDT 2024                                 
2024-11-29 15:23:13,213 WARN 2972202 [main] u.g.c.l.e.g.s.GeoBrowser.searchGeoRecords(534) | No records retained from query - all filtered out; number of raw records was 0              
2024-11-29 15:23:13,213 INFO 2972202 [main] u.g.c.a.GeoGrabberCli.seekRewindPoint(400) | Reached end of records while seeking.                                                           
2024-11-29 15:23:13,214 INFO 2972202 [main] u.g.c.a.GeoGrabberCli.browseDatasets(307) | Could not find the rewind point.   `

**Comment by arteymix** [comment] 2024-12-03 17:55
The issue is that we stop on the first empty record we hit. However, sometimes GEO returns an empty response as some kind of error. We need to detect those and retry as per the retry policy.

**Comment by arteymix** [comment] 2024-12-03 19:30
OK, I got a reliable solution in 8e6f4e8b4d2ab85543f5aeb0902d430a5414b5ff.

GEO actually tells us how many records the search has (we'll be able to use that for #1297). With that information, we can check if a page contains the expected number of records and retry it if necessary.

**Comment by arteymix** [comment] 2024-12-03 19:35
You will see an error like this:

![image](https://github.com/user-attachments/assets/0b7774ee-cca9-4e72-8e54-be5ee2992040)

**Comment by arteymix** [comment] 2024-12-03 23:23
Fixed with 545c96ba52e75d3b43bce99f464a19491a5a1df8.

**Closed by arteymix** 2024-12-03 23:23 UTC
Labels: bug, cli
