### ISSUE TITLE
Incorrect data loaded for GSE16035 (all samples have same data) on production

### ISSUE THREAD

**Issue by aman-s** [PavlidisLab/Gemma#78] opened 2019-05-03 20:10 UTC
EDIT: https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=11940

For eeID:11940: The diagnostics (PCA, correlations) and visualize expression tabs on Gemma don't seem to reflect the expression values seen in the soft files obtained on GEO.

However, the soft file stored in /cosmos/scratch/curator-scratch/arraydata/GEO/GSE16035 seems to be the correct (and most up to date) soft file available from GEO (which is why a parsing problem seems most likely).

**Comment by ppavlidis** [comment] 2019-05-06 17:37
Cannot reproduce on current dev head (which is not far ahead of production). I tested this and is parses and loads correctly. My prediction is that deleting it and reloading will fix the problem. Odd.

**Comment by aman-s** [comment] 2019-05-06 21:08
Problem still persists

**Comment by ppavlidis** [comment] 2019-05-06 21:51
Aman reports that this is specific for this data set, other data sets on this platform load fine

**Comment by ppavlidis** [comment] 2021-06-17 18:05
Current version of the data is https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?id=14630

**Comment by ppavlidis** [comment] 2021-06-17 18:28
I don't know what to do about this, the SOFT file is fine, loading a test is fine. Some deeper debugging is needed

**Comment by ppavlidis** [comment] 2022-09-02 20:23
This data set is still in the system but comes up as blacklisted due to unsupported platform, which isn't correct. I'm moving this over to a curation issue.

**Closed by ppavlidis** 2022-09-02 20:23 UTC
