### ISSUE TITLE
Gene names and symbols are the same in differential expression datasets

### ISSUE THREAD

**Issue by yavyx** [PavlidisLab/Gemma#290] opened 2022-01-13 21:34 UTC
When fetching differential expression results (ex. https://gemma.msl.ubc.ca/rest/v2/resultSets/500184?&offset=0&limit=20&sort=%2Bid) with the "text: tab-separated-values" header, the `gene_official_symbol` and `gene_name` columns are identical, both contain the gene symbols. `gene_name` should contain longer gene descriptions which can be found in the JSON output.

**Comment by arteymix** [comment] 2022-01-28 22:29
This is caused by using the `name` instead of the `officialName` attribute in the gene model.

@yavyx Is it okay to replace the `gene_name` with `gene_official_name` in the TSV header?

**Comment by arteymix** [comment] 2022-02-01 20:17
This has been fixed in 34d1f5677ba0f9ae2489ecdee83b2f026271d8ed. I'll deploy it on the dev right away.

**Comment by arteymix** [comment] 2022-02-01 20:39
![image](https://user-images.githubusercontent.com/1318477/152047307-c2168b66-232e-4d94-b948-6be133dfb48b.png)

I consider this fixed. It's essentially the same output in the JSON representation: both `officialName` and `name` are exposed.

**Closed by arteymix** 2022-02-01 20:39 UTC
Labels: bug, rest-api

**Comment by ppavlidis** [comment] 2022-02-01 20:54
If we want to streamline the JSON, I would leave name and description out. Official symbol and official name is all that is needed.

It's an artifact of ChromosomeFeatures (gene is a subclass) being Describable. We long ago decided it was important to be clear about the exact definition of "name" and "description" for Genes which is why we have officialSymbol and officialName in addition but it is obviously a potential source of confusion (leading to this issue) to have name and description as well. Not a big deal but especially if we don't expose it to the outside.

**Comment by arteymix** [comment] 2022-02-01 21:15
We would first need to make sure that it is not being used anywhere before removing those. It's been historically part of the `GeneValueObject`.

**Comment by ppavlidis** [comment] 2022-02-01 21:23
Naturally, but I would argue that is shouldn't be used if it is.

**Comment by ppavlidis** [comment] 2022-02-01 21:25
It's not easy to remove per se because it is baked into our data model, but it doesn't have to be in the JSON, that's all I was saying. It's a very minor issue.

**Comment by arteymix** [comment] 2022-02-01 21:36
If it's not used in the frontend, we can use Jackson directives to exclude them. 

@ppavlidis do you happen to know if the frontend uses Jackson for JSON serialization?

**Comment by arteymix** [comment] 2022-02-01 21:42
If the frontend doesn't use Jackson (which, I think, is correct), then we can use those directives to simplify the REST endpoints without being too concerned with breaking anything.

**Comment by ppavlidis** [comment] 2022-02-01 22:03
> If the frontend doesn't use Jackson (which, I think, is correct), then we can use those directives to simplify the REST endpoints without being too concerned with breaking anything.

Yes, I don't think we use Jackson for the web interface - DWR is the conduit for all JSON and I'm not aware of Jackson being in the stack.

**Comment by arteymix** [comment] 2022-02-01 22:27
I recall I switched all our code to use [org.json](https://github.com/stleary/JSON-java), so it should be safe from those annotations. The serialization for the RESTful API is handled by Jersey via Jackson.
