### ISSUE TITLE
Treat single lane RNA-Seq experiment more kindly

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#129] opened 2021-01-28 19:14 UTC
Gemma is not treating single lane RNA-Seq experiments as if they have no batch information, penalizing their GEEQ scores and flagging them with a "no batch info" status.

 - [x] return a success code for submitting batch info with a single lane (just tested and it works!)
 - [x] don't show the "no batch info" status, or maybe replace it with a "single lane" status
 - [x] don't penalize single lane experiments

Examples of single lane experiments: [GSE142485](https://gemma.msl.ubc.ca/expressionExperiment/showExpressionExperiment.html?shortName=GSE142485)

Relates to #97

**Comment by ppavlidis** [comment] 2021-01-28 19:24
I agree. Our framework was designed with microarrays in mind, where in theory we could have batch information, but don't, and we don't like that. If we can determine there are no batches, we should handle that with the "no batch effect" kind of indicator.

As an aside: any data set (not just the case mentioned here) could still have massive batch effects from steps earlier in processing (library construction etc.) that aren't captured in the information we use to define batching. So "no batch effect" is "as far as we know".

**Comment by ppavlidis** [comment] 2021-02-23 23:07
Want to comment/discuss that currently we distinguish between (1) "has enough information for us to conclude there aren't batches" and (2) "we had no way to tell".

In the first case, we can say "no batch effect" (basically) but in the other, we're complaining that the information is just missing. I'm inclined to keep it this way. Pretty much every Illumina BeadChip microarray data set is just missing any (easily usable) batch information, but we know they do have batches.

The issue is that we don't really record anything in the system to indicate case 1. 

Just to document what's happening in the RNA-seq case:

In PavlidisLab/GemmaCuration#48 (GSE156689), the headers lack information on lane etc. other than resolving read pairs so we can't tell. It has this style of FASTQ headers

`@SRR12502405.1.1 1 length=100`

Which is completely useless AFICT so it's case 2. (The data set in question has 22 samples, which is probably more than one lane, for what it's worth; if I'm wrong that somehow that header can be interpreted better, that would be good to know; Also note that if the GEO submission uses multiple GPLs we would use those as the basis for batching even if it has this  style of headers)

In contrast, the example @arteymix  mentioned GSE142485 has this style:

`@SRR10753167.1.1 D00257:339:CDM1FANXX:6:2212:1154:2063 length=61`

The values in the middle are lane etc. but they are the same for all samples.

So this issue (#129) is addressing the case 1 where we *do* have good information on device/run/lane and they are all the same for all samples. 

Of course, that "good information" is still lacking any true confirmation that there aren't batches - we don't have access to how the libraries were constructed, etc. In fact that's the only reason I bring up the distinction between "we know there are no batches" and "we can't tell". It's a somewhat weak distinction.

**Comment by ppavlidis** [comment] 2021-02-23 23:19
My fix does the following (partly hard to test locally, so have to proceed cautiously)

- When determining if an experiment has batch information, we check if we have stored FASTQ headers. This was a bug (the comparable check for microarrays is for run dates, which was working correctly)
- If we decide there is no need to create a batch factor, we add a SingleBatchDeterminationEvent which is a subclass of BatchInformationFetchingEvent. Currently I am not using this for anything, but it makes it explicit what happened.

**Comment by ppavlidis** [comment] 2021-02-24 18:47
I added tests so this really should be okay now, but I haven't explicitly addressed how "single-batch" experiments show up on the web interface.

**Closed** 2021-06-22 00:05 UTC
