### ISSUE TITLE
resultSets endpoint takes much longer to run in dev

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/Gemma#733] opened 2023-06-12 23:58 UTC
- works fine (~6 secs): https://gemma.msl.ubc.ca/rest/v2/resultSets/548729
- takes prohibitively longer and sometimes fails with error 502: https://dev.gemma.msl.ubc.ca/rest/v2/resultSets/548729

If it's a dev environment specific issue it doesn't really matter but wouldn't want to have it sneak into production

**Comment by arteymix** [comment] 2023-06-13 16:06
It's definitely a regression. I'll investigate the underlying query.

**Comment by arteymix** [comment] 2023-06-13 17:15
It looks like the genes are not fetched very efficiently. I'll add them to the jointure.

**Comment by arteymix** [comment] 2023-06-13 17:21
It takes about 6 seconds now!

**Comment by arteymix** [comment] 2023-06-13 17:22
There's a lot of room for improvement in the query because we gather a cross-product of probes and contrast which could be done in two separate queries. I'll open a separate issue for that.

**Comment by arteymix** [comment] 2023-06-15 22:50
The definitive fix is in dfb517f85a45144178d6ab9f949e63589521d65a as I've addressed some cache-related performance issues that was making the endpoint very slow on the dev server.

**Comment by arteymix** [comment] 2023-06-29 17:23
I'm attempting a new fix in f74727f3cc31a771d322a2629657c467327b2bc6 and also introducing bb4350fb470e5789d94fa3f350f1de33e0fe1621 to enhance caching of probes and genes.

**Comment by oganm** [comment] 2023-07-14 01:09
This issue doesn't seem to have been fully resolved. The endpoint still works prohibitively slow on dev

**Comment by arteymix** [comment] 2023-07-14 02:53
Ok, I also want to look into downloading datasets at the same time.

**Comment by arteymix** [comment] 2023-07-31 17:25
OK, it turns out that I removed the `hibernate.jdbc..fetch_size` option as part of cleaning up our Hibernate options. The download should be lightning fast. I might try to tune that value a little bit to see if I can make it perform even better.

**Comment by arteymix** [comment] 2023-07-31 17:28
I'm also removing vectors and analysis results caches because they are not useful: we never retrieve individual vectors/results by ID. However, once we fetch them, we have to write to the cache.

**Closed** 2023-07-31 17:29 UTC
Labels: high priority, regression, performance

**Comment by arteymix** [comment] 2023-08-02 01:55
I'm investigating why the performance is so poor. I managed to run the SQL query myself and it takes a few seconds to gather the results.

**Comment by arteymix** [comment] 2023-08-02 01:56
The same applies to obtaining data vectors.

**Comment by arteymix** [comment] 2023-08-02 18:21
Ok, turns out I was missing the `sequenceDatabaseEntry` fetch jointure in my query. The performance should be equal now if not slightly better.

Fixed in ab605bbf922b8978a5d57e334a937d12286b7b93
